export const PLAN_UPDATE_TEMPLATE = 'plan.update.template'
export const PLAN_UPDATE_THEME = 'plan.update.theme'
export const PLAN_UPDATE_CACHE = 'plan.update.cache'
export const PLAN_FILTER = 'plan.filter'
export const PLAN_ADD = 'plan.add'
export const PLAN_EDIT = 'plan.edit'
export const PLAN_UPDATE = 'plan.update'
export const PLAN_REMOVE = 'plan.remove'
export const PLAN_REPLACE = 'plan.replace'
export const PLAN_DELETE = 'plan.delete'
export const PLAN_ARCHIVE = 'plan.archive'
export const PLAN_CLOSE_PANELS = 'plan.close.panels'

export const TOOLBAR_ARCHIVES_TOGGLE_HIGHLIGHT = 'toolbar.archives.toggle.highlight'
export const TOOLBAR_TRASH_TOGGLE_HIGHLIGHT = 'toolbar.trash.toggle.highlight'
export const TOOLBAR_SETTING_TOGGLE_HIGHLIGHT = 'toolbar.setting.toggle.highlight'

export const PANEL_VIEW_UPDATE = 'panel.view.update'
export const PANEL_VIEW_OPEN = 'panel.view.open'
export const PANEL_VIEW_CLOSE = 'panel.view.close'
export const PANEL_VIEW_EMPTY = 'panel.view.empty'

export const PANEL_ADD_OPEN = 'panel.add.open'
export const PANEL_ADD_CLOSE = 'panel.add.close'
export const PANEL_ADD_TOGGLE = 'panel.add.toggle'
export const PANEL_ADD_EMPTY = 'panel.add.empty'

export const PANEL_EDIT_UPDATE = 'panel.edit.update'
export const PANEL_EDIT_OPEN = 'panel.edit.open'
export const PANEL_EDIT_CLOSE = 'panel.edit.close'
export const PANEL_EDIT_EMPTY = 'panel.edit.empty'

export const PANEL_ARCHIVES_ADD = 'panel.archives.add'
export const PANEL_ARCHIVES_OPEN = 'panel.archives.open'
export const PANEL_ARCHIVES_CLOSE = 'panel.archives.close'
export const PANEL_ARCHIVES_TOGGLE = 'panel.archives.toggle'
export const PANEL_ARCHIVES_EMPTY = 'panel.archives.empty'

export const PANEL_TRASH_ADD = 'panel.trash.add'
export const PANEL_TRASH_PUSH = 'panel.trash.push'
export const PANEL_TRASH_OPEN = 'panel.trash.open'
export const PANEL_TRASH_CLOSE = 'panel.trash.close'
export const PANEL_TRASH_TOGGLE = 'panel.trash.toggle'
export const PANEL_TRASH_EMPTY = 'panel.trash.empty'

export const PANEL_SETTING_OPEN = 'panel.setting.open'
export const PANEL_SETTING_CLOSE = 'panel.setting.close'
export const PANEL_SETTING_TOGGLE = 'panel.setting.toggle'

export const COLUMNS_OPEN = 'columns.open'
export const COLUMNS_CLOSE = 'columns.close'
export const COLUMNS_FILTER = 'columns.filter'
export const COLUMNS_ADD = 'columns.add'
export const COLUMNS_PUSH = 'columns.push'
export const COLUMNS_EDIT = 'columns.edit'
export const COLUMNS_DELETE = 'columns.delete'
export const COLUMNS_EMPTY = 'columns.empty'
